= Custom policies UI backend

This backend is to serve (data to) the UI for Custom Policies

For some functionality it relies on the Engine part.

== Get started

To get started (locally) you can build a local docker image with Postgres, that has example tables set up and then
run this via Docker-Compose, which starts Postgres and a local Kafka instance for use with the Engine.

[source,shell]
----
cd helpers
sh build-local-pg.sh
docker-compose up
----

The UI backend is written in Java and can be compiled via

[source,shell]
----
mvn package
----

Which also runs some Rest-API tests (under the hood it starts a postgres instance in a container).

When developing you can use Quarkus hot-reload

[source,shell]
----
mvn compile quarkus:dev
----

.NOTE
The backend requires a valid `x-rh-identity` to be supplied on calls.
For testing purposes you can take the one that is stored in
link:src/test/resources/rhid.txt


== List existing policies

[source,shell]
----
curl  -Hx-rh-identity:`cat src/test/resources/rhid.txt` http://localhost:8080/api/custom-policies/v1.0/policies/<id> # id = 1 or 2
----


== List fact keys (for the UI)
[source,shell]
----
curl  -Hx-rh-identity:`cat src/test/resources/rhid.txt` http://localhost:8080//api/custom-policies/v1.0/facts
----

== OpenAPI Endpoint / Swagger-UI

OpenAPI spec of the API is available under http://localhost:8080/api/custom-policies/v1.0/openapi.json

When the server is running in dev mode, there is also the Swagger-UI available under
http://localhost:8080/swagger-ui/

== Container usage

The `deploy/` directory contains a script to create a container image of the engine.

[source,shell]
----
cd deploy
sh create_docker_image.sh
----

To run the image you need to pass some parameters:

[source,shell]
----
docker run -it -p 8080:8080 \                       # <1>
    -e engine/mp-rest/url=http://172.31.7.7:8083    # <2>
    -e quarkus.datasource.url=jdbc:postgres://1.2.3.4:5432/postgres \ # <3>
     cp-app
----
<1> Expose the internal port.
<2> Url of the engine (Rule execution engine)
<3> Database URL of your postgres instance

You can also pass the Postgres user name + password - see Dockerfile.

