---
apiVersion: v1
kind: Template
metadata:
  name: policies-ui-backend
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: policies-ui-backend
    labels:
      app: policies-ui-backend
  spec:
    envName: ${ENV_NAME}
    dependencies:
    - notifications-backend
    - policies-engine
    - rbac
    database:
      sharedDbAppName: policies-engine
    testing:
      iqePlugin: policies
    deployments:
    - name: policies-ui-backend
      minReplicas: ${{MIN_REPLICAS}}
      web: true
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        resources:
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
        volumes:
        - name: rds-client-ca
          emptyDir: {}
        volumeMounts:
        - name: rds-client-ca
          mountPath: /tmp
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 420
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 420
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        env:
        - name: POLICIES_HISTORY_ENABLED
          value: ${POLICIES_HISTORY_ENABLED}
        - name: QUARKUS_HTTP_PORT
          value: "8000"
        - name: QUARKUS_LOG_CLOUDWATCH_ENABLED
          value: ${CLOUDWATCH_ENABLED}
        - name: QUARKUS_LOG_CLOUDWATCH_LOG_STREAM_NAME
          value: ${HOSTNAME}
        - name: QUARKUS_LOG_SENTRY
          value: ${SENTRY_ENABLED}
        - name: QUARKUS_LOG_SENTRY_DSN
          value: https://1c5a768a78364f8e8f18c962b89bab49@o271843.ingest.sentry.io/5217683?environment=${ENV_NAME}
        - name: QUARKUS_LOG_SENTRY_ENVIRONMENT
          value: ${ENV_NAME}
parameters:
- name: CLOUDWATCH_ENABLED
  description: Enable Cloudwatch (or not)
  value: "false"
- name: CPU_LIMIT
  description: CPU limit on ephemeral
  value: 500m
- name: CPU_REQUEST
  description: CPU request on ephemeral
  value: 500m
- name: ENV_NAME
  description: ClowdEnvironment name (stage, prod, ephemeral)
  required: true
- name: IMAGE
  description: Image URL
  value: quay.io/cloudservices/policies-ui-backend
- name: IMAGE_TAG
  description: Image tag
  value: latest
- name: MEMORY_LIMIT
  description: Memory limit on ephemeral
  value: 500Mi
- name: MEMORY_REQUEST
  description: Memory request on ephemeral
  value: 250Mi
- name: MIN_REPLICAS
  value: "1"
- name: POLICIES_HISTORY_ENABLED
  description: Enable history entries retrieval from policies-history (Postgres)
  value: "true"
- name: SENTRY_ENABLED
  description: Enable Sentry (or not)
  value: "false"
