---
apiVersion: v1
kind: Template
metadata:
  name: policies-ui-backend-do-nothing
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: policies-ui-backend-do-nothing-${IMAGE_TAG}-${JOBID}
  spec:
    template:
      spec:
        containers:
        - name: policies-do-nothing
          image: quay.io/app-sre/ubi8-ubi-minimal:8.6-902
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi 
          command: ["/bin/sh"]
          args: ["-c", "exit 0"]
        restartPolicy: Never
parameters:
- name: IMAGE_TAG
  value: ''
  required: true
- name: JOBID
  generate: expression
  from: "[0-9a-f]{7}"
