{
 "title": "Policies",
 "tags": [ "policies" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 5, "w": 16, "x": 0, "y": 9 },
     "options": {
      "content": "# Policies\n Remember to save updates to panel json/definition to [policies-ui-backend repo](https://github.com/RedHatInsights/policies-ui-backend/blob/master/.rhcicd/grafana-dashboard-insights-policies.configmap.yaml).\n\n To view:\n- Prod metrics, use [the prod Grafana instance](https://grafana.app-sre.devshift.net/d/zEvWtW6Mz/p?orgId=1&refresh=5m): select \"datasource=crcp01ue1-prometheus\" \n \n- Stage metrics, use [the stage Grafana instance](https://grafana.stage.devshift.net/d/zEvWtW6Mz/p?orgId=1&refresh=5m): select \"datasource=crcs02ue1-prometheus\" "
     }
    },
    {
     "title": "Policies Engine persistent volume disk usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "100 * kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"policies-engine-data\"} / (kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"policies-engine-data\"} + kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"policies-engine-data\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Up/Down \"policies-ui-backend\"",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 10 },
     "format": "none",
     "valueName": "min",
     "targets": [
      {
       "expr": "up{service=\"policies-ui-backend\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "restarts \"policies-ui-backend\"",
     "type": "singlestat",
     "description": "This shows the number of restarts for the latest pod that's running in that time period",
     "gridPos": { "h": 3, "w": 6, "x": 5, "y": 10 },
     "repeat": "service",
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kube_pod_container_status_restarts_total{container=\"policies-ui-backend\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Up/Down \"policies-engine\"",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 5, "x": 11, "y": 10 },
     "repeat": "service",
     "format": "none",
     "valueName": "min",
     "targets": [
      {
       "expr": "up{service=\"policies-engine\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "restarts \"policies-engine\"",
     "type": "singlestat",
     "description": "This shows the number of restarts for the latest pod that's running in that time period",
     "gridPos": { "h": 3, "w": 5, "x": 16, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kube_pod_container_status_restarts_total{container=\"policies-engine\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "3Scale",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "3scale API Requests",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(increase(api_3scale_gateway_api_status{exported_service=\"policies\"}[$__range]))"
      }
     ]
    },
    {
     "title": "2xx Status",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 5, "y": 3 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(api_3scale_gateway_api_status{exported_service=\"policies\",status=\"2xx\"})"
      }
     ]
    },
    {
     "title": "4xx Status",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 10, "y": 3 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(api_3scale_gateway_api_status{exported_service=\"policies\",status=\"4xx\"})"
      }
     ]
    },
    {
     "title": "HTTP Requests",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 0, "y": 5 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(api_3scale_gateway_api_status{exported_service=\"policies\",status=\"2xx\"}) + sum(api_3scale_gateway_api_status{exported_service=\"policies\",status=\"3xx\"}) + sum(api_3scale_gateway_api_status{exported_service=\"policies\",status=\"4xx\"}) + sum(api_3scale_gateway_api_status{exported_service=\"policies\",status=\"5xx\"})"
      }
     ]
    },
    {
     "title": "3xx Status",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 5, "y": 5 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(api_3scale_gateway_api_status{exported_service=\"policies\",status=\"3xx\"}) "
      }
     ]
    },
    {
     "title": "5xx Status",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 10, "y": 5 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(api_3scale_gateway_api_status{exported_service=\"policies\",status=\"5xx\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages In Per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kafka_server_brokertopicmetrics_messagesin_total{topic=~\"platform.notifications.ingress\",topic!=\"\"}[1m]))"
      }
     ]
    },
    {
     "title": "Bytes Output Per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kafka_server_brokertopicmetrics_bytesout_total{topic=~\"platform.notifications.ingress\"}[1m])) by (topic)"
      }
     ]
    },
    {
     "title": "Request Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(api_3scale_gateway_api_time_count{exported_service=\"policies\"}[5m]))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "rate",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum(increase(api_3scale_gateway_api_time_count{exported_service=\"policies\"}[5m]))",
       "legendFormat": "count"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage \"policies-ui-backend\"",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "repeat": "service",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container=\"policies-ui-backend\"}) BY (pod, namespace)"
      }
     ]
    },
    {
     "title": "Memory usage \"policies-engine\"",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container=\"policies-engine\"}) BY (pod, namespace)"
      }
     ]
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Payload processed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "rate(engine_input_processed_total{service=\"policies-engine\"}[2m])",
     "legendFormat": "Received (Per second)"
    },
    {
     "expr": "rate(engine_input_processed_errors_total{service=\"policies-engine\"}[2m])",
     "legendFormat": "Errors (Absolute)"
    }
   ]
  },
  {
   "title": "Messages sent from the engine",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "engine_actions_notifications_aggregated_total{service=\"policies-engine\"}",
     "legendFormat": "Aggregated total"
    }
   ]
  },
  {
   "title": "Rollups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true
  },
  {
   "title": "RDS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true
  },
  {
   "title": "Evaluating",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true
  }
 ]
}