---
apiVersion: v1
kind: Template
metadata:
  name: policies-ui-backend
objects:
- apiVersion: v1
  kind: Secret # For ephemeral/local environment
  metadata:
    name: policies-ui-backend-secrets
    labels:
      app: policies-ui-backend
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: policies-ui-backend
    labels:
      app: policies-ui-backend
      clowdapp: policies-ui-backend
  spec:
    envName: ${ENV_NAME}
    deployments:
    - name: policies-ui-backend
      minReplicas: ${{MIN_REPLICAS}}
      web: true
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/live
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 420
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/ready
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 420
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 5
        env:
        - name: APP_NAME
          value: ${APP_NAME}
        - name: ENV_NAME
          value: ${ENV_NAME}
        - name: PATH_PREFIX
          value: ${PATH_PREFIX}
        - name: ENGINE_MP_REST_URL
          value: http://policies-engine:8080
        - name: RBAC_URL
          value: ${RBAC_SCHEME}://${RBAC_HOST}:${RBAC_PORT}
        - name: RBAC_MP_REST_URL
          value: ${RBAC_SCHEME}://${RBAC_HOST}:${RBAC_PORT}
        - name: QUARKUS_LOG_SENTRY_ENVIRONMENT
          value: ${ENV_NAME}
        - name: QUARKUS_LOG_SENTRY_DSN
          value: >-
            https://1c5a768a78364f8e8f18c962b89bab49@o271843.ingest.sentry.io/5217683?environment=${ENV_NAME}
        - name: QUARKUS_LOG_SENTRY
          value: ${SENTRY_ENABLED}
        - name: NOTIFICATIONS_MP_REST_URL
          value: ${NOTIFICATIONS_MP_REST_URL}
        - name: CLOWDER_FILE
          value: ${CLOWDER_FILE}
        - name: CLOWDER_ENABLED
          value: ${CLOWDER_ENABLED}
        resources:
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}
        volumes:
        - emptyDir: {}
          name: tmpdir
        volumeMounts:
        - mountPath: /tmp
          name: tmpdir
    database:
      name: policies-ui-backend-db
      version: 12
    optionalDependencies:
      - rbac
      - ingress

parameters:
- name: LOG_LEVEL
  value: INFO
- description: Cpu limit of service
  name: CPU_LIMIT
  value: 1000m
- description: memory limit of service
  name: MEMORY_LIMIT
  value: 4Gi
- name: CPU_REQUEST
  description: The cpu request
  value: 500m
- name: MEMORY_REQUEST
  description: The memory request
  value: 2Gi
- name: MIN_REPLICAS
  value: '1'
- description: Image tag
  name: IMAGE_TAG
  required: true
- description: Image name
  name: IMAGE
  value: quay.io/cloudservices/policies-ui-backend
- description: Determines Clowder deployment
  name: CLOWDER_ENABLED
  value: "false"
- description: ClowdEnv Name (stage, prod, ephemeral)
  name: ENV_NAME
  required: true
- name: CLOWDER_FILE
  value: /cdapp/cdappconfig.json
  description: default path for cdappconfig file
- name: RBAC_SCHEME
  displayName: Rbac Service Scheme
  description: Scheme to use for the RBAC service URL. Can be either http or https
  value: http
- name: RBAC_HOST
  displayName: Rbac Service Host
  description: Host to use for the RBAC service URL.
  value: "rbac-service"
- name: RBAC_PORT
  displayName: Rbac Service Port
  description: Port to use for the RBAC service URL.
  value: "8080"
- name: RBAC_SCHEME
  displayName: Rbac Service Scheme
  description: Scheme to use for the RBAC service URL. Can be either http or https
  value: http
- name: APP_NAME
  displayName: Application Name
  description: Application name to be used in request paths. Only used when PATH_PREFIX is also specified.
  value: policies
- name: PATH_PREFIX
  displayName: Path Prefix
  description: Base path for the API
- name: SENTRY_ENABLED
  displayName: Enable Sentry (or not)
  value: "false"
- name: NOTIFICATIONS_MP_REST_URL
  value: "http://notifications-backend.notifications-ci.svc:8080/"
