{
 "title": "Policies Dashboard",
 "tags": [ "policies" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "environment",
    "query": "crcs02ue1-prometheus, crcp01ue1-prometheus"
   }
  ]
 },
 "panels": [
  {
   "title": "policies-engine - http requests per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{container=\"policies-engine\"}[5m]) * 60) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "policies-engine - processed input",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(engine_input_processed_total[5m]))",
     "legendFormat": "processed total"
    },
    {
     "expr": "sum(rate(engine_input_processed_errors_total[5m]))",
     "legendFormat": "processed errors total"
    },
    {
     "expr": "sum(rate(engine_input_rejected_total[5m]))",
     "legendFormat": "rejected total"
    }
   ]
  },
  {
   "title": "policies-engine notifications aggregated & processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(engine_actions_notifications_processed_total[5m]))",
     "legendFormat": "processed"
    },
    {
     "expr": "sum(rate(engine_actions_notifications_aggregated_total[5m]))",
     "legendFormat": "aggregated"
    }
   ]
  },
  {
   "title": "Engine persistent volume disk usage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"policies-engine-data\"} / (kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"policies-engine-data\"} + kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"policies-engine-data\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "policies engine - number of restarts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{container=\"policies-engine\"}"
    }
   ]
  },
  {
   "title": "policies-engine - memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace='policies-prod',container=\"policies-engine\"}) BY (pod, namespace)"
    }
   ]
  },
  {
   "title": "policies-ui-backend - number of restarts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{container=\"policies-ui-backend\"}"
    }
   ]
  },
  {
   "title": "policies-ui-backend - memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace='policies-prod',container=\"policies-ui-backend\"}) BY (pod, namespace)"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_3scale_gateway_api_time_count{exported_service=\"policies\"}[5m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(increase(api_3scale_gateway_api_time_count{exported_service=\"policies\"}[5m]))",
     "legendFormat": "count"
    }
   ]
  },
  { "title": "3Scale", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "API error rate",
   "type": "graph",
   "description": "Proportion of 5xx status codes returned from this service.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_3scale_gateway_api_status{exported_service=\"policies\",status=\"5xx\"}[5m])) / sum(rate(api_3scale_gateway_api_time_count{exported_service=\"policies\"}[5m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 32 },
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_time_bucket{exported_service=\"policies\"}[5m])) by (le)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "policies-ui-backend - threads used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_thread_count{container=\"policies-ui-backend\"}",
     "legendFormat": "JVM Base Thread Count (Deamon and non Deamon)"
    }
   ]
  },
  {
   "title": "policies-ui-backend - heap used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "base_memory_usedHeap_bytes{container=\"policies-ui-backend\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " base_memory_maxHeap_bytes{container=\"policies-ui-backend\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "base_memory_usedHeap_bytes{container=\"policies-ui-backend\"}",
     "legendFormat": "Usage %"
    }
   ]
  }
 ]
}